Задание 1

In [ ]:
import numpy as np

Задание 2

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
zeros = np.zeros(5)
print("zeros:", zeros)

zeros: [0. 0. 0. 0. 0.]


In [ ]:
ones = np.ones(6)
print("ones:", ones)


ones: [1. 1. 1. 1. 1. 1.]


In [ ]:
arr = np.arange(5)
print("arange:", arr)

arange: [0 1 2 3 4]


In [ ]:
empty_arr = np.empty(5)
print("empty:", empty_arr)

empty: [4.9e-324 9.9e-324 1.5e-323 2.0e-323 2.5e-323]


In [ ]:
full_arr = np.full(5, 7)
print("full:", full_arr)

full: [7 7 7 7 7]


Задание 3

In [ ]:
array= np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])

print("Массив:")
print(array)
print("\nАтрибуты массива:")
print(f"array.shape = {array.shape}")
print(f"array.dtype = {array.dtype}")

Массив:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Атрибуты массива:
array.shape = (3, 4)
array.dtype = int64


Задание 4

In [ ]:
arr_1d = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print("Исходный массив:", arr_1d)

# Получение отдельных элементов
print(f"arr_1d[0] = {arr_1d[0]}")# Первый элемент
print(f"arr_1d[4] = {arr_1d[4]}")# Пятый элемент
print(f"arr_1d[-1] = {arr_1d[-1]}")# Последний элемент
print(f"arr_1d[-2] = {arr_1d[-2]}")# Предпоследний элемент

Исходный массив: [10 20 30 40 50 60 70 80 90]
arr_1d[0] = 10
arr_1d[4] = 50
arr_1d[-1] = 90
arr_1d[-2] = 80


In [ ]:
print(f"arr_1d[2:5] = {arr_1d[2:5]}")# Элементы с индексом 2 до 4 (5 не включительно)
print(f"arr_1d[:4] = {arr_1d[:4]}") # Элементы с начала до индекса 3
print(f"arr_1d[5:] = {arr_1d[5:]}")# Элементы с индекса 5 до конца
print(f"arr_1d[::2] = {arr_1d[::2]}") # Каждый второй элемент
print(f"arr_1d[1::2] = {arr_1d[1::2]}")# Каждый второй, начиная с индекса 1
print(f"arr_1d[::-1] = {arr_1d[::-1]}")# Массив в обратном порядке

arr_1d[2:5] = [30 40 50]
arr_1d[:4] = [10 20 30 40]
arr_1d[5:] = [60 70 80 90]
arr_1d[::2] = [10 30 50 70 90]
arr_1d[1::2] = [20 40 60 80]
arr_1d[::-1] = [90 80 70 60 50 40 30 20 10]


In [ ]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])
print("Двумерный массив:")
print(arr_2d)

print(f"arr_2d[0, 0] = {arr_2d[0, 0]}")      # Элемент в строке 0, столбец 0
print(f"arr_2d[2, 1] = {arr_2d[2, 1]}")      # Элемент в строке 2, столбец 1
print(f"arr_2d[-1, -1] = {arr_2d[-1, -1]}")  # Последний элемент последней строки
print(f"arr_2d[1] = {arr_2d[1]}")            # Вся вторая строка

Двумерный массив:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
arr_2d[0, 0] = 1
arr_2d[2, 1] = 10
arr_2d[-1, -1] = 16
arr_2d[1] = [5 6 7 8]


In [ ]:
print("arr_2d[0:2, 1:3] - первые 2 строки, столбцы 1-2:")
print(arr_2d[0:2, 1:3])

print("\narr_2d[:, 2] - все строки, столбец 2:")
print(arr_2d[:, 2])

print("\narr_2d[1:3, :] - строки 1-2, все столбцы:")
print(arr_2d[1:3, :])

print("\narr_2d[::2, ::2] - каждая вторая строка и столбец:")
print(arr_2d[::2, ::2])

arr_2d[0:2, 1:3] - первые 2 строки, столбцы 1-2:
[[2 3]
 [6 7]]

arr_2d[:, 2] - все строки, столбец 2:
[ 3  7 11 15]

arr_2d[1:3, :] - строки 1-2, все столбцы:
[[ 5  6  7  8]
 [ 9 10 11 12]]

arr_2d[::2, ::2] - каждая вторая строка и столбец:
[[ 1  3]
 [ 9 11]]


Задание 5

In [ ]:
# Создаем массивы для примеров
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])

print(f"Массив a: {a}")
print(f"Массив b: {b}")
print("Массив c:")
print(c)
print("Массив d:")
print(d)

Массив a: [1 2 3 4 5]
Массив b: [10 20 30 40 50]
Массив c:
[[1 2]
 [3 4]]
Массив d:
[[5 6]
 [7 8]]


In [ ]:
print(f"a + b = {a + b}")          # Сложение
print(f"b - a = {b - a}")          # Вычитание
print(f"a * b = {a * b}")          # Умножение
print(f"b / a = {b / a}")          # Деление
print(f"a ** 2 = {a ** 2}")        # Возведение в степень
print(f"a % 3 = {a % 3}")          # Остаток от деления

print("\nМатричные операции:")
print("c + d =")
print(c + d)
print("\nc * d =")
print(c * d)

a + b = [11 22 33 44 55]
b - a = [ 9 18 27 36 45]
a * b = [ 10  40  90 160 250]
b / a = [10. 10. 10. 10. 10.]
a ** 2 = [ 1  4  9 16 25]
a % 3 = [1 2 0 1 2]

Матричные операции:
c + d =
[[ 6  8]
 [10 12]]

c * d =
[[ 5 12]
 [21 32]]


In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean_1d = np.mean(arr_1d)
print(f"Массив: {arr_1d}")
print(f"Среднее значение: {mean_1d}")
print(f"Проверка: сумма = {np.sum(arr_1d)}, количество = {len(arr_1d)}")
print(f"Расчет: {np.sum(arr_1d)} / {len(arr_1d)} = {np.sum(arr_1d) / len(arr_1d)}")

Массив: [ 1  2  3  4  5  6  7  8  9 10]
Среднее значение: 5.5
Проверка: сумма = 55, количество = 10
Расчет: 55 / 10 = 5.5
